import json
import datetime
from typing import Dict, Any

def export_json(report: Dict[str, Any], filepath: str):
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

def generate_markdown_report(report: Dict[str, Any]) -> str:
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        f"# ??? SecScan-CLI Audit Report: {report['target']}",
        f"**Date:** {now}  ",
        f"**Security Score:** **{report['score']} / 100** (Grade: **{report['grade']}**)\n",
        "---",
        "## ?? SSL/TLS Posture",
        f"- **Valid:** {report['ssl']['valid']}",
        f"- **Issuer:** {report['ssl']['issuer']}",
        f"- **Days Remaining:** {report['ssl']['days_remaining']}",
        f"- **TLS Version:** {report['ssl']['tls_version']}",
        f"- **Cipher Suite:** {report['ssl']['cipher']}\n",
        "## ?? HTTP Security Headers",
        "| Category | Status | Points | Value / Recommendation |",
        "| :--- | :---: | :---: | :--- |"
    ]

    for h in report["headers"]:
        val_or_rec = h["value"] if h["status"] == "PASS" else h["recommendation"]
        lines.append(f"| {h['category']} | {h['status']} | +{h['points']} | {val_or_rec} |")

    lines.append("\n---\n*Report generated by SecScan-CLI*")
    return "\n".join(lines)
